### PR TITLE
Add configuration generation script

### PR DESCRIPTION
**Pull request by kristjan**
@rpdillon @heidi

This is a convenient starting point for anyone installing `h`, though they'll
surely want to modify what's generated.

### CODE REVIEW

**Comment by tcollier** [comment]
LGTM!

**Comment by rpdillon** [comment]
This was supplanted by scripts/config.  Not sure this should be merged
anymore, but Kristjan should weigh in.

**Comment by kristjan** [comment]
Seems like `scripts/config` will just get out of date and requires at least as much work as running this generator. I've got my config, so doesn't matter to me either way.

**Comment by rpdillon** [comment]
> I've got my config, so doesn't matter to me either way.

The point of the shared config is that when apps are added, only one engineer need change the config in order to update all other engineers' configs.

> requires at least as much work as running this generator.

True, but irrelevant.  Running the generator yields an arbitrary, incomplete output, where apps like acapella-experimental are eclipsed by api-events (which no one uses), but acapella-production is eclipsed by apartmentlist-production, and bedroc is favored over baloo and beacon.  Having to manually sort out the mess produced by this code is much more more complex and time consuming than just updating the shared config that *already exists*.

**Comment by rpdillon** [comment]
Removed prior comment, since this is part of the open-source code, which has utility beyond our specific problems of app management.  For the 90% use case, this is probably a great starting point.  I don't think it works well for us right now, though.

**Comment by heidi** [comment]
@kristjan bump

**Pull request merged**
